[package]
name = "notability"
version = "0.1.0"
authors = ["Andrea Cognolato <andrecogno@hotmail.it>"]
edition = "2018"

[dependencies]
svg = "0.5.12"
roxmltree = "0.6.0"
byteorder = "1.3.1"
base64 = "0.10.1"
